[package]
name = "delegate_rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.44.0", features = ["macros", "sync"] }

[dev-dependencies]
tokio = { version = "1.44.0", features = ["rt-multi-thread"] }
