[package]
name = "delegate_rs"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["delegate", "macros"]

[dependencies]
delegate = { path = "./delegate" }
macros = { path = "./macros" }

[dev-dependencies]
tokio = { version = "1.44.1", features = ["rt", "macros"]}
